name: quanttools
dependencies:
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - XlsxWriter
  - networkx
  - astropy
  - pybind11
  - openpyxl
  - plotly
  - requests
  - pip:
    - streamlit
    - riskfolio-lib
    - stockstats
    - arch
    - cvxpy
    - yfinance
    - tensorflow
    - tf-quant-finance