name: quanttools
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - statsmodels
  - XlsxWriter
  - networkx
  - astropy
  - pybind11
  - streamlit
  - openpyxl
  - plotly
  - PIL
  - requests
  - pip:
    - riskfolio-lib
    - stockstats
    - arch
    - cvxpy
    - yfinance